package main

import (
	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"

	_ "github.com/aerosystems/nix-junior-chat-back/docs" // docs are generated by Swag CLI, you have to import it
)

func (app *Config) NewRouter() *echo.Echo {
	e := echo.New()

	e.GET("/docs/*", echoSwagger.WrapHandler)

	e.GET("/v1/user", app.BaseHandler.User, app.AuthUserMiddleware())

	e.POST("/v1/user/register", app.BaseHandler.Registration)
	e.POST("/v1/user/login", app.BaseHandler.Login)
	e.POST("/v1/user/logout", app.BaseHandler.Logout, app.AuthTokenMiddleware())

	e.PUT("/v1/user/update-password", app.BaseHandler.UpdatePassword, app.AuthUserMiddleware())
	e.PUT("/v1/user/update-username", app.BaseHandler.UpdateUsername, app.AuthUserMiddleware())
	e.PUT("/v1/user/update-image", app.BaseHandler.UpdateImage, app.AuthUserMiddleware())

	e.POST("/v1/tokens/refresh", app.BaseHandler.RefreshTokens, app.AuthTokenMiddleware())

	//Social relations
	e.GET("/v1/search", app.BaseHandler.Search, app.AuthUserMiddleware())
	e.POST("/v1/follow", app.BaseHandler.Follow, app.AuthUserMiddleware())
	e.POST("/v1/block", app.BaseHandler.Block, app.AuthUserMiddleware())

	//Chat
	e.GET("/ws/chat", app.BaseHandler.Chat, app.AuthUserMiddleware())

	return e
}
